/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-12-12 00:20:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.makelogin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script language=\"javascript\" src=\"loginscript.js\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/6498553759.js\" async\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Jua&family=Kablammo&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	font-family: \"Jua\", sans-serif;\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: rgb(0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header>nav {\r\n");
      out.write("	height: 150px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: row;\r\n");
      out.write("	flex-wrap: nowrap;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.nav_futlogo {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: row;\r\n");
      out.write("	justify-content: flex-start;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav>ul {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: row;\r\n");
      out.write("	flex-wrap: nowrap;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.nav_futlogo i {\r\n");
      out.write("	color: rgb(0, 0, 0);\r\n");
      out.write("	font-size: 32px;\r\n");
      out.write("	margin: 5px;\r\n");
      out.write("}\r\n");
      out.write(".bun{\r\n");
      out.write("width: 70px;\r\n");
      out.write("height: 50px;\r\n");
      out.write("}\r\n");
      out.write(".epl{\r\n");
      out.write("width: 50px;\r\n");
      out.write("height: 50px;\r\n");
      out.write("}\r\n");
      out.write(".sea{\r\n");
      out.write("width: 50px;\r\n");
      out.write("height: 50px;\r\n");
      out.write("}\r\n");
      out.write(".la{\r\n");
      out.write("width: 50px;\r\n");
      out.write("height: 50px;\r\n");
      out.write("}\r\n");
      out.write("div.nav_futlogo a:hover {\r\n");
      out.write("	color: blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.nav_menu {\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: row;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.nav_menu li {\r\n");
      out.write("	padding: 10px 40px;\r\n");
      out.write("	font-size: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.nav_menu li a i {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.nav_menu li a:hover {\r\n");
      out.write("	color: blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.nav_icon {\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: row;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.nav_icon a {\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.nav_icon a:hover {\r\n");
      out.write("	color: blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("i {\r\n");
      out.write("	font-size: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown {\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content {\r\n");
      out.write("	display: none;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	min-width: 150px;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.dropdown-content a {\r\n");
      out.write("	display: block;\r\n");
      out.write("	padding: 14px 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown:hover .dropdown-content {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"onLoad()\">\r\n");
      out.write("	<header>\r\n");
      out.write("		<nav>\r\n");
      out.write("			<div class=\"nav_futlogo\">\r\n");
      out.write("				<a href=\"#\"><i class=\"fa-solid fa-futbol\"></i></a> <a href=\"#\">메인메뉴</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<ul class=\"nav_menu\">\r\n");
      out.write("					<li><a href=\"#\"><img src=\"./media/LaLiga_EA_Sports_2023_Vertical_Logo.svg.png\"alt=\"laliga\" class=\"la\"><br><span>LALIGA</span></a></li>\r\n");
      out.write("					<li><a href=\"#\"><img src=\"./media/pl-main-logo.png\"alt=\"laliga\" class=\"epl\"></i><br><span>EPL</span></i></a></li>\r\n");
      out.write("					<li><a href=\"#\"><img src=\"./media/bundesliga-logo.png\"alt=\"laliga\" class=\"bun\"><br><span>BUNDES</span></a></li>\r\n");
      out.write("					<li><a href=\"#\"><img src=\"./media/Serie_A_logo_2022.svg.png\"alt=\"laliga\" class=\"sea\"></i><br><span>SERIE</span></a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<ul class=\"nav_icon\">\r\n");
      out.write("				<li><a href=\"#\"><i class=\"fa-regular fa-comment\"></i></a></li>\r\n");
      out.write("				<li><a href=\"#\"><i class=\"fa-solid fa-question\"></i></a></li>\r\n");
      out.write("				<li><a href=\"#\"><i class=\"fa-solid fa-bars\"></i></a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("	<main>\r\n");
      out.write("		<form method=\"post\" action=\"regProc.jsp\" class=\"regForm\">\r\n");
      out.write("			<table border=\"1\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" align=\"center\">회원 가입 입력</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"center\">아이디 :</td>\r\n");
      out.write("					<td><input type=\"text\" id=\"id\" /> <input type=\"button\"\r\n");
      out.write("						value=\"중복확인\" onClick=\"idCheck()\" /><span></span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"center\">패스워드 :</td>\r\n");
      out.write("					<td><input type=\"password\" id=\"pwd\" /><br> <span></span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"center\">패스워드 확인:</td>\r\n");
      out.write("					<td><input type=\"password\" id=\"pwd2\" /><span></span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"center\">이름 :</td>\r\n");
      out.write("					<td><input type=\"text\" id=\"name\" /><span></span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"center\">전화번호 :</td>\r\n");
      out.write("					<td><select id=\"phone1\">\r\n");
      out.write("							<option value=\"010\">010</option>\r\n");
      out.write("					</select> - <input type=\"text\" id=\"phone2\" size=\"5\" /> - <input type=\"text\"\r\n");
      out.write("						id=\"phone3\" size=\"5\" /></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"center\">이메일 :</td>\r\n");
      out.write("					<td><input type=\"email\" id=\"email\" /></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"center\">생년월일</td>\r\n");
      out.write("					<td><input type=\"date\" id=\"birthday\" id=\"birthday\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"center\">우편번호 :</td>\r\n");
      out.write("					<td><input type=\"text\" id=\"zipcode\" /> <input type=\"button\"\r\n");
      out.write("						value=\"찾기\" onClick=\"zipCheck()\" /></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"center\">주소 :</td>\r\n");
      out.write("					<td><input type=\"text\" id=\"address1\" size=\"50\" /></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"center\">상세주소 :</td>\r\n");
      out.write("					<td><input type=\"text\" id=\"address2\" size=\"30\" /></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" align=\"center\"><input type=\"submit\"\r\n");
      out.write("						value=\"회원가입\" onClick=\"\" />&nbsp;&nbsp; <input type=\"reset\"\r\n");
      out.write("						value=\"다시입력\" /></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</form>\r\n");
      out.write("	</main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
